### ISSUE TITLE
Конструкция #ifndef, #define ... #endif

### ISSUE THREAD

**Issue by R1mok** [Timeslort/heaven#1]
В файле LogicalElement.h следует вводить:

`#ifndef _NAME_H`
`#define _NAME_H`
И в конце файла
`#endif`
`#ifndef` используется для предотвращения многократного включения заголовочных файлов или включения/исключения какого-то кода.

**Comment by Timeslort** [comment]
Но я использую директиву #pragma once которая делает тоже самое

**Comment by R1mok** [comment]
Хорошо, просто я пользуюсь методами, которые были на лекциях
